### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by MONEYKORDHAHA** [useragents/TikTok-Share-Botter#1]
when i do pip install -r requirements.txt it says pip is not a recognized as an internal or external command how do i fix this?
![image_2022-04-23_152147339](https://user-images.githubusercontent.com/104264317/164909985-7cb71418-731e-44a9-a92f-26beabec209b.png)

**Comment by neko5star** [comment]
> when i do pip install -r requirements.txt it says pip is not a recognized as an internal or external command how do i fix this?
> ![image_2022-04-23_152147339](https://user-images.githubusercontent.com/104264317/164909985-7cb71418-731e-44a9-a92f-26beabec209b.png)
> 

dm me on discord i can help neko#4484

**Comment by MONEYKORDHAHA** [comment]
> > when i do pip install -r requirements.txt it says pip is not a recognized as an internal or external command how do i fix this?
> > ![image_2022-04-23_152147339](https://user-images.githubusercontent.com/104264317/164909985-7cb71418-731e-44a9-a92f-26beabec209b.png)
> 
> dm me on discord i can help neko#4484

yo i added you

**Comment by useragents** [comment]
@MONEYKORDHAHA Please view [here](https://pip.pypa.io/en/stable/cli/pip_install/) to learn how to install PIP.
