### ISSUE TITLE
Malwear in project Download on VM

### ISSUE THREAD

**Issue by ILostmyDowen** [useragents/TikTok-Share-Botter#2]
Just put your tool through Virus total and it flagged 14 security vendors

Virustotal link: https://www.virustotal.com/gui/file/831f75287644efd74e22e736578be937bfb9c4f1df95a46b509f842c2dd8edc9

It detected 

ALYac

Gen:Variant.Tedy.105817
Antiy-AVL

Trojan/Generic.ASMalwS.35664D8
Arcabit

Trojan.Tedy.D19D59
BitDefender

Gen:Variant.Tedy.105817
Emsisoft

Gen:Variant.Tedy.105817 (B)
eScan

Gen:Variant.Tedy.105817
GData

Gen:Variant.Tedy.105817
Gridinsoft

Ransom.Win64.Casur.oa!s1
Jiangmin

TrojanSpy.Python.am
MAX

Malware (ai Score=84)
McAfee

Artemis!07272750CFD9
Microsoft

Trojan:Script/Sabsik.FL.B!ml
Trellix (FireEye)

Gen:Variant.Tedy.105817
Zillya

Trojan.Disco.Win64.211

So please Be sure to run this in VM

**Comment by useragents** [comment]
There is no malware or other in the EXE file, it was compiled with pyinstaller 5.0 and Python version 3.8. They are false positives due to the compilation, feel free to decompile the EXE using uncompyle6 before creating an issue saying that this is malware when it is not. Appreciate your concern 👍

**Comment by useragents** [comment]
You can also research how pyinstaller compiles Python scripts to realize why there are false positives. Read more [here](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg)

**Comment by useragents** [comment]
If you are still precautious about the EXE version, that is not a problem. Feel free to use the Python script. :)

**Comment by ILostmyDowen** [comment]
Got you I should of done that first before stating it was a virus. Your projects are HQ and pretty good. Keep up the good work

**Comment by useragents** [comment]
Appreciate it. 👍
