### ISSUE TITLE
Caps?

### ISSUE THREAD

**Issue by xTqc** [useragents/TikTok-Share-Botter#5]
Stopped working at 17.9k (with the exe). Thoughts?

**Comment by useragents** [comment]
How many threads are you running?

**Comment by useragents** [comment]
Lower your amount of threads and this issue will not occur.

**Comment by xTqc** [comment]
Alr tried that it just takes a bit to load then at the top of cmd it says

Shares: 0 - Errors: It just counts up to however many threads i'm running then pauses then counts up again.
